2023-05-14 00:00:05,166 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:00:17,168 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:03:49,698 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:05:06,110 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:07:59,643 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:08:29,379 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:09:43,990 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:10:37,535 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:11:03,537 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:11:23,649 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:11:54,910 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:13:23,741 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:13:48,755 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:14:21,371 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:15:04,018 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:15:29,545 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:15:58,762 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:16:33,679 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:17:54,719 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:18:20,301 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:18:36,082 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:19:03,736 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:19:22,275 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:19:44,321 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:19:56,944 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:20:30,925 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:20:58,025 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:21:26,809 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:21:54,690 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:22:33,930 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:24:16,399 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:24:32,390 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:24:53,706 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:26:09,313 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 00:26:37,165 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 01:37:01,618 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 01:37:52,186 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 01:43:51,419 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 01:54:03,788 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 01:54:06,466 ERROR: Exception on /app/static/background-icons/guitar-solid.svg [GET] [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/errors.py", line 6, in not_found_error
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/base.html", line 63, in top-level template code
    {% include "nav.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/nav.html", line 4, in top-level template code
    {% if user_data.authorised %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user_data' is undefined
2023-05-14 01:54:09,905 ERROR: Exception on /app/static/background-icons/guitar-solid.svg [GET] [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/errors.py", line 6, in not_found_error
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/base.html", line 63, in top-level template code
    {% include "nav.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/nav.html", line 4, in top-level template code
    {% if user_data.authorised %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user_data' is undefined
2023-05-14 01:54:10,935 ERROR: Exception on /app/static/background-icons/guitar-solid.svg [GET] [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/errors.py", line 6, in not_found_error
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/base.html", line 63, in top-level template code
    {% include "nav.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/nav.html", line 4, in top-level template code
    {% if user_data.authorised %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user_data' is undefined
2023-05-14 01:54:11,451 ERROR: Exception on /app/static/background-icons/guitar-solid.svg [GET] [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/errors.py", line 6, in not_found_error
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/base.html", line 63, in top-level template code
    {% include "nav.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/nav.html", line 4, in top-level template code
    {% if user_data.authorised %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user_data' is undefined
2023-05-14 01:54:25,634 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 01:54:27,228 ERROR: Exception on /app/static/background-icons/guitar-solid.svg [GET] [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/errors.py", line 6, in not_found_error
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/base.html", line 63, in top-level template code
    {% include "nav.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/nav.html", line 4, in top-level template code
    {% if user_data.authorised %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user_data' is undefined
2023-05-14 01:55:25,607 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 01:55:31,608 ERROR: Exception on /Songversation/app/static/background-icons/guitar-solid.svg [GET] [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/errors.py", line 6, in not_found_error
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/base.html", line 63, in top-level template code
    {% include "nav.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/nav.html", line 4, in top-level template code
    {% if user_data.authorised %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user_data' is undefined
2023-05-14 01:55:40,406 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 01:56:37,139 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 01:57:03,442 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:02:59,453 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:04:58,241 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:07:55,076 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:08:59,160 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:09:14,691 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:09:35,767 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:09:50,172 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:10:05,173 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:10:19,205 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:10:30,429 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:11:14,660 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:12:17,385 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:12:34,852 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:12:45,533 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:13:00,089 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:13:07,248 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:13:22,140 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:14:37,055 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:15:20,576 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:16:00,414 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:18:16,456 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:19:20,664 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:20:15,533 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:20:35,287 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:21:20,867 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:29:35,120 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:30:46,257 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:31:33,205 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:32:35,990 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:37:56,966 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:38:14,592 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:38:26,105 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:38:49,189 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:39:08,976 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:39:44,244 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:42:47,348 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:45:11,738 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:46:28,132 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:47:13,714 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:48:49,648 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:50:40,007 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:51:06,141 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:52:04,595 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:52:54,554 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:54:20,410 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:54:58,475 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:55:27,227 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:57:46,777 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:58:28,457 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:59:05,473 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 02:59:25,986 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:00:43,306 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:01:02,598 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:01:48,294 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:02:33,283 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:03:26,353 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:04:10,334 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:04:25,796 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:04:49,920 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:05:10,174 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:05:25,266 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:05:36,291 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:06:44,419 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:07:11,976 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:07:40,051 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:08:29,232 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:09:53,742 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:10:52,715 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:13:56,939 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:14:38,715 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:14:56,217 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:16:05,047 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:17:06,299 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:17:33,938 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 03:17:57,161 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 22:12:05,263 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 22:19:57,765 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 22:20:05,310 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 22:20:08,098 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 22:29:21,399 ERROR: Exception on /api/get-track-lyrics [GET] [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/api/spotify_api.py", line 124, in get_track_lyrics
    get_tracks(track_ids)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/cache_manager/track_cache.py", line 31, in get_tracks
    track_cache = Track(id = track['id'], name = track['name'], preview_url = track['preview_url'], image_url = track['album']['images'][0]['url'])
                                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2023-05-14 23:17:27,140 INFO: Starting Songversation... [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/__init__.py:42]
2023-05-14 23:17:29,514 ERROR: Exception on / [GET] [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/spotipy/oauth2.py", line 588, in refresh_access_token
    response.raise_for_status()
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/routes.py", line 21, in index
    return render_template('index.html', title='Home - Songversation', user_data=SpotifyWebUserData())
                                                                                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/helpers/spotify_helper.py", line 80, in __init__
    sp = SpotifyHelper()
         ^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/helpers/spotify_helper.py", line 19, in __init__
    session['token_info'], authorised = self.get_token()
                                        ^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/helpers/spotify_helper.py", line 51, in get_token
    token_info = sp_oauth.refresh_access_token(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/spotipy/oauth2.py", line 596, in refresh_access_token
    self._handle_oauth_error(http_error)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/spotipy/oauth2.py", line 146, in _handle_oauth_error
    raise SpotifyOauthError(
spotipy.oauth2.SpotifyOauthError: error: invalid_grant, error_description: Refresh token revoked
2023-05-14 23:17:29,780 ERROR: Exception on /favicon.ico [GET] [in /Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1788, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1770, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/errors.py", line 6, in not_found_error
    return render_template('errors/404.html'), 404
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/base.html", line 36, in top-level template code
    {% include "nav.html" %}
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/app/templates/nav.html", line 4, in top-level template code
    {% if user_data.authorised %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GihadCoorey11/Desktop/CITS3403/Songversation/Songversation-venv/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'user_data' is undefined
